package transformationGenerator.fitness.functions.interfaces;

import transformationGenerator.fitness.functions.BalancedFitnessFunction;
import transformationGenerator.fitness.functions.BalancedFitnessFunctionBasedOnStructureAsFallback;
import transformationGenerator.fitness.functions.BalancedFitnessFunctionBasedOnStructureAsFallbackAndImportantAssociations;
import transformationGenerator.fitness.functions.BalancedFitnessFunctionBasedOnlyOnStructure;
import transformationGenerator.fitness.functions.PropertyFocusedFitnessFunctionBasedOnStructureAsFallback;
import transformationGenerator.fitness.functions.StructureFocusedFitnessFunction;

public interface IFitnessFunctionFactory {
	BalancedFitnessFunction createBalancedFitnessFunction();

	StructureFocusedFitnessFunction createStructureFocusedFitnessFunction();

	BalancedFitnessFunctionBasedOnlyOnStructure createBalancedFitnessFunctionBasedOnlyOnStructure();
	
	BalancedFitnessFunctionBasedOnStructureAsFallback createBalancedFitnessFunctionBasedOnStructureAsFallback();
	
	PropertyFocusedFitnessFunctionBasedOnStructureAsFallback createPropertyFocusedFitnessFunctionBasedOnStructureAsFallback();
	
	BalancedFitnessFunctionBasedOnStructureAsFallbackAndImportantAssociations createBalancedFitnessFunctionBasedOnStructureAsFallbackAndImportantAssociations();
}
